#' Student's t-test (with automatic diagnostics)
#'
#' Performs Student's t-test to compare means between two independent groups,
#' with automatic checks for normality and homogeneity of variances.
#' If assumptions are violated, the Mann–Whitney test is automatically applied
#' (without generating a plot).
#'
#' @param ... Two numeric vectors or a data frame with exactly two columns.
#' @param title Plot title (string). Default: "t-test".
#' @param xlab X-axis label in the plot (string). Default: "Group".
#' @param ylab Y-axis label in the plot (string). Default: "Value".
#' @param style Plot aesthetic generated by the function.
#' @param help Logical. If TRUE, shows a detailed explanation of the function.
#'        Default: FALSE.
#' @param verbose Logical. If TRUE, prints detailed messages. Default: TRUE.
#' @return Invisible list with summary, test result, method and (optionally) plot.
#' @export
#'
#' @examples
#' set.seed(123)
#' df <- data.frame(
#'   control = rnorm(30, 10),
#'   treatment = rnorm(30, 15)
#' )
#' test.t(df)

test.t <- function(..., title = "t-test", xlab = "Group", ylab = "Value",
                   help = FALSE, verbose = TRUE, style = 1) {

  args <- list(...)

  # --- Quick help ---
  if (help) {
    if (verbose) {
      message("
Function test.t()

Description:
  Performs Student's t-test to compare the means of two independent groups,
  with automatic checks for normality (Shapiro–Wilk) and homogeneity of variances
  (Levene's test).

If assumptions are violated, the Mann–Whitney test is automatically applied
and no plot is generated.

Accepted inputs:
  - Two numeric vectors (e.g., group1, group2)
  - A data frame with exactly two numeric columns

Example:
  set.seed(123)
  df <- data.frame(
    control = rnorm(30, 10),
    treatment = rnorm(30, 15)
  )
  test.t(df)
")
    }
    return(invisible(NULL))
  }

  # --- Detect data frame input ---
  if (length(args) == 1 && is.data.frame(args[[1]])) {
    df <- args[[1]]
    if (ncol(df) != 2) {
      stop("The data frame must contain exactly two numeric columns.")
    }
    groups <- as.list(df)
    group_names <- colnames(df)
  } else {
    groups <- args
    if (length(groups) != 2) {
      stop("Provide exactly two groups or a data frame with two columns.")
    }
    group_names <- sapply(substitute(list(...))[-1], deparse)
  }

  # --- Validation ---
  if (!all(sapply(groups, is.numeric))) {
    stop("Both groups must be numeric.")
  }
  if (any(sapply(groups, function(g) sd(g, na.rm = TRUE) == 0))) {
    stop("One of the groups has zero variance (constant values).")
  }

  # --- Required packages ---
  required_packages <- c("ggplot2", "dplyr", "car", "ggdist")
  for (pkg in required_packages) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
      stop(
        paste0(
          "Package '", pkg,
          "' is not installed. Install it with install.packages('", pkg, "')"
        )
      )
    }
  }

  # --- Build long-format data frame ---
  values <- unlist(groups)
  group <- factor(
    rep(group_names, times = sapply(groups, length)),
    levels = group_names
  )
  data <- data.frame(value = values, group = group)

  # --- Normality test (Shapiro–Wilk) ---
  normality <- sapply(groups, function(g) {
    if (length(g) < 3) return(NA)
    stats::shapiro.test(g[!is.na(g)])$p.value
  })
  is_normal <- all(normality > 0.05, na.rm = TRUE)

  # --- Homogeneity test (Levene) ---
  homogeneity <- tryCatch(
    car::leveneTest(value ~ group, data = data, na.action = na.omit),
    error = function(e) data.frame(`Pr(>F)` = NA)
  )
  is_homogeneous <- !is.na(homogeneity$`Pr(>F)`[1]) &&
    homogeneity$`Pr(>F)`[1] > 0.05

  # --- Test selection ---
  if (is_normal && is_homogeneous) {
    result <- stats::t.test(groups[[1]], groups[[2]])
    method <- "Student's t-test"
    generate_plot <- TRUE
  } else {
    result <- stats::wilcox.test(groups[[1]], groups[[2]])
    method <- "Mann–Whitney test"
    generate_plot <- FALSE
  }

  p_value <- result$p.value

  # --- Descriptive summary ---
  summary_stats <- data |>
    dplyr::group_by(group) |>
    dplyr::summarise(
      Mean = round(mean(value, na.rm = TRUE), 2),
      SD = round(sd(value, na.rm = TRUE), 2),
      .groups = "drop"
    )

  if (verbose) {
    message("\nDescriptive summary by group:")
    print(summary_stats)
  }

  # --- Conditional plot generation ---
  if (generate_plot) {

    p_label <- if (p_value < 0.001) {
      "p < 0.001"
    } else {
      paste0("p = ", signif(p_value, 3))
    }

    signif_label <- if (p_value < 0.001) {
      "***"
    } else if (p_value < 0.01) {
      "**"
    } else if (p_value < 0.05) {
      "*"
    } else {
      ""
    }

    y_pos <- max(values, na.rm = TRUE) +
      0.1 * diff(range(values, na.rm = TRUE))

    vivid_colors <- scales::hue_pal()(length(unique(data$group)))

    # --------------------------
    # STYLE 1 (Boxplot + jitter)
    # --------------------------
    if (style == 1) {
      g <- ggplot2::ggplot(data, ggplot2::aes(x = group, y = value, fill = group)) +
        ggplot2::geom_boxplot(alpha = 0.7, outlier.shape = NA) +
        ggplot2::geom_jitter(width = 0.1, alpha = 0.4, color = "black") +
        ggplot2::annotate(
          "text", x = mean(1:2), y = y_pos,
          label = signif_label, size = 6
        ) +
        ggplot2::theme_minimal(base_size = 12) +
        ggplot2::scale_fill_brewer(palette = "Set1") +
        ggplot2::labs(
          title = title,
          subtitle = paste0(method, ": ", p_label),
          x = "",
          y = ylab
        ) +
        ggplot2::theme(
          legend.position = "none",
          axis.text.x = ggplot2::element_text(
            angle = 45, hjust = 1, size = 12
          )
        )
    }

    # --------------------------
    # STYLE 2 (Clean violin + minimal boxplot)
    # --------------------------
    if (style == 2) {
      g <- ggplot2::ggplot(data, ggplot2::aes(x = group, y = value, fill = group)) +
        ggplot2::geom_violin(
          trim = FALSE, alpha = .55,
          color = NA, adjust = .6
        ) +
        ggplot2::geom_boxplot(
          width = .18, outlier.shape = NA,
          color = "gray20", linewidth = .4
        ) +
        ggplot2::geom_point(
          position = ggplot2::position_jitter(width = .1),
          alpha = .4, size = 1.8, color = "gray25"
        ) +
        ggplot2::annotate(
          "text", x = mean(1:2), y = y_pos,
          label = signif_label, size = 7
        ) +
        ggplot2::scale_fill_manual(values = vivid_colors) +
        ggplot2::theme_minimal(base_size = 12) +
        ggplot2::labs(
          title = title,
          subtitle = paste0(method, ": ", p_label),
          x = "",
          y = ylab
        ) +
        ggplot2::theme(
          legend.position = "none",
          axis.text.x = ggplot2::element_text(
            angle = 45, hjust = 1, size = 12
          )
        )
    }

    # --------------------------
    # STYLE 3 (Premium monochrome)
    # --------------------------
    if (style == 3) {
      g <- ggplot2::ggplot(data, ggplot2::aes(group, value)) +
        ggplot2::geom_violin(fill = "gray85", color = NA) +
        ggplot2::geom_boxplot(width = .18, fill = "white") +
        ggplot2::geom_point(
          position = ggplot2::position_jitter(width = .1),
          color = "gray20", alpha = .4
        ) +
        ggplot2::annotate(
          "text", x = 1.5, y = y_pos,
          label = signif_label, size = 7
        ) +
        ggplot2::theme_minimal(base_size = 12) +
        ggplot2::labs(
          title = title,
          subtitle = paste0(method, ": ", p_label),
          x = "",
          y = ylab
        ) +
        ggplot2::theme(
          legend.position = "none",
          axis.text.x = ggplot2::element_text(
            angle = 45, hjust = 1, size = 12
          )
        )
    }

    # --------------------------
    # STYLE 4 (ggdist half-eye + median)
    # --------------------------
    if (style == 4) {
      g <- ggplot2::ggplot(
        data,
        ggplot2::aes(x = group, y = value, fill = group)
      ) +
        ggdist::stat_halfeye(
          adjust = 0.6,
          width = 0.6,
          .width = c(0.5, 0.8, 0.95),
          justification = -0.2,
          slab_color = "gray20",
          interval_color = "gray20"
        ) +
        ggplot2::geom_point(
          position = ggplot2::position_nudge(x = 0.15),
          size = 1.1, alpha = 0.4, color = "black"
        ) +
        ggdist::stat_pointinterval(
          position = ggplot2::position_nudge(x = 0.2),
          point_color = "black",
          interval_color = "black",
          .width = 0.95
        ) +
        ggplot2::annotate(
          "text", x = mean(1:2), y = y_pos,
          label = signif_label, size = 6, fontface = "bold"
        ) +
        ggplot2::theme_minimal(base_size = 12) +
        ggplot2::scale_fill_brewer(palette = "Set1") +
        ggplot2::labs(
          title = title,
          subtitle = paste0(method, ": ", p_label),
          x = "",
          y = ylab
        ) +
        ggplot2::theme(
          legend.position = "none",
          axis.text.x = ggplot2::element_text(
            angle = 45, hjust = 1, size = 12
          )
        )
    }

    print(g)

  } else {
    if (verbose) {
      message("\nAssumptions violated: plot not generated.")
    }
    g <- NULL
  }

  invisible(list(
    summary = summary_stats,
    result = result,
    method = method,
    normality = normality,
    homogeneity = homogeneity,
    plot = g
  ))
}
